# Generated by Django 4.1.7 on 2023-10-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=20, verbose_name='User Email')),
                ('password', models.CharField(max_length=20, verbose_name='Password')),
            ],
        ),
    ]
