# Generated by Django 4.1.7 on 2023-10-25 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_users_name_alter_users_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.CharField(blank=True, max_length=1024, verbose_name='Description')),
                ('location', models.CharField(max_length=1024, verbose_name='Location')),
                ('pic', models.ImageField(upload_to='books/')),
                ('price', models.IntegerField()),
                ('available', models.BooleanField()),
            ],
        ),
    ]
