# Generated by Django 4.1.7 on 2023-10-25 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='author',
            field=models.CharField(default='', max_length=50, verbose_name='Author'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='books',
            name='rating',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
