# Generated by Django 4.1.7 on 2023-10-25 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_reservations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('email', models.EmailField(max_length=20, verbose_name='Email')),
                ('bookid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book', to='core.books')),
            ],
        ),
    ]
