# Generated by Django 4.1.7 on 2023-10-25 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservations',
            name='name',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='name',
        ),
        migrations.AlterField(
            model_name='reservations',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emaili', to='core.users'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emailid', to='core.users'),
        ),
    ]
