# Generated by Django 4.1.7 on 2023-10-25 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_reservations_name_remove_wishlist_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forums',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('forum', models.CharField(max_length=100, verbose_name='Forum Name')),
                ('message', models.CharField(max_length=1024, verbose_name='Message')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emai', to='core.users')),
            ],
        ),
    ]
