# Generated by Django 4.1.7 on 2023-10-26 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forums',
            name='email',
        ),
        migrations.RemoveField(
            model_name='forums',
            name='message',
        ),
    ]
