# Generated by Django 4.1.7 on 2023-10-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_forums_email_remove_forums_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='url',
            field=models.CharField(max_length=1024, null=True, verbose_name='Link To Buy'),
        ),
    ]
