# Generated by Django 4.1.7 on 2023-10-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_books_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='url',
            field=models.CharField(max_length=1024, verbose_name='Link To Buy'),
        ),
    ]
